language: php
php:
  - "5.6"
  - "5.5"

notifications:
  email:
    - jnesselr@harding.edu

# whitelist
branches:
  only:
    - master
    - laravel

before_install:
  - sudo apt-get update > /dev/null

install:
  # Install the packages we need
  - sudo apt-get install -y --force-yes php5-mysql php-pear build-essential php5-curl php5-dev libmagic-dev sqlite3

  # Install composer
  - composer self-update
  - composer install
  
script:
  - phpunit
