---
abstract: 'G-code generator for 3D printers'
author:
  - 'Alessandro Ranellucci <aar@cpan.org>'
build_requires:
  IO::Scalar: 0.10
  Test::More: 0.10
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Slic3r
provides:
  Slic3r:
    file: lib/Slic3r.pm
    version: v0.9.9
  Slic3r::Config:
    file: lib/Slic3r/Config.pm
    version: 0
  Slic3r::ExPolygon:
    file: lib/Slic3r/ExPolygon.pm
    version: 0
  Slic3r::ExPolygon::Collection:
    file: lib/Slic3r/ExPolygon.pm
    version: 0
  Slic3r::Extruder:
    file: lib/Slic3r/Extruder.pm
    version: 0
  Slic3r::ExtrusionLoop:
    file: lib/Slic3r/ExtrusionLoop.pm
    version: 0
  Slic3r::ExtrusionLoop::Packed:
    file: lib/Slic3r/ExtrusionLoop.pm
    version: 0
  Slic3r::ExtrusionPath:
    file: lib/Slic3r/ExtrusionPath.pm
    version: 0
  Slic3r::ExtrusionPath::Arc:
    file: lib/Slic3r/ExtrusionPath/Arc.pm
    version: 0
  Slic3r::ExtrusionPath::Collection:
    file: lib/Slic3r/ExtrusionPath/Collection.pm
    version: 0
  Slic3r::ExtrusionPath::Packed:
    file: lib/Slic3r/ExtrusionPath.pm
    version: 0
  Slic3r::Fill:
    file: lib/Slic3r/Fill.pm
    version: 0
  Slic3r::Fill::ArchimedeanChords:
    file: lib/Slic3r/Fill/ArchimedeanChords.pm
    version: 0
  Slic3r::Fill::Base:
    file: lib/Slic3r/Fill/Base.pm
    version: 0
  Slic3r::Fill::Concentric:
    file: lib/Slic3r/Fill/Concentric.pm
    version: 0
  Slic3r::Fill::Flowsnake:
    file: lib/Slic3r/Fill/Flowsnake.pm
    version: 0
  Slic3r::Fill::HilbertCurve:
    file: lib/Slic3r/Fill/HilbertCurve.pm
    version: 0
  Slic3r::Fill::Honeycomb:
    file: lib/Slic3r/Fill/Honeycomb.pm
    version: 0
  Slic3r::Fill::Line:
    file: lib/Slic3r/Fill/Line.pm
    version: 0
  Slic3r::Fill::OctagramSpiral:
    file: lib/Slic3r/Fill/OctagramSpiral.pm
    version: 0
  Slic3r::Fill::PlanePath:
    file: lib/Slic3r/Fill/PlanePath.pm
    version: 0
  Slic3r::Fill::Rectilinear:
    file: lib/Slic3r/Fill/Rectilinear.pm
    version: 0
  Slic3r::Flow:
    file: lib/Slic3r/Flow.pm
    version: 0
  Slic3r::Flow::Bridge:
    file: lib/Slic3r/Flow.pm
    version: 0
  Slic3r::Format::AMF:
    file: lib/Slic3r/Format/AMF.pm
    version: 0
  Slic3r::Format::AMF::Parser:
    file: lib/Slic3r/Format/AMF/Parser.pm
    version: 0
  Slic3r::Format::OBJ:
    file: lib/Slic3r/Format/OBJ.pm
    version: 0
  Slic3r::Format::STL:
    file: lib/Slic3r/Format/STL.pm
    version: 0
  Slic3r::GCode:
    file: lib/Slic3r/GCode.pm
    version: 0
  Slic3r::GCode::MotionPlanner:
    file: lib/Slic3r/GCode/MotionPlanner.pm
    version: 0
  Slic3r::GUI:
    file: lib/Slic3r/GUI.pm
    version: 0
  Slic3r::GUI::AboutDialog:
    file: lib/Slic3r/GUI/AboutDialog.pm
    version: 0
  Slic3r::GUI::AboutDialog::Logo:
    file: lib/Slic3r/GUI/AboutDialog.pm
    version: 0
  Slic3r::GUI::ConfigOptionsGroup:
    file: lib/Slic3r/GUI/OptionsGroup.pm
    version: 0
  Slic3r::GUI::ConfigWizard:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Index:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::Bed:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::BedTemperature:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::Filament:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::Finished:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::Firmware:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::Nozzle:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::Temperature:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::ConfigWizard::Page::Welcome:
    file: lib/Slic3r/GUI/ConfigWizard.pm
    version: 0
  Slic3r::GUI::Notifier:
    file: lib/Slic3r/GUI.pm
    version: 0
  Slic3r::GUI::OptionsGroup:
    file: lib/Slic3r/GUI/OptionsGroup.pm
    version: 0
  Slic3r::GUI::OptionsGroup::StaticTextLine:
    file: lib/Slic3r/GUI/OptionsGroup.pm
    version: 0
  Slic3r::GUI::Plater:
    file: lib/Slic3r/GUI/Plater.pm
    version: 0
  Slic3r::GUI::Plater::DropTarget:
    file: lib/Slic3r/GUI/Plater.pm
    version: 0
  Slic3r::GUI::Plater::Object:
    file: lib/Slic3r/GUI/Plater.pm
    version: 0
  Slic3r::GUI::Plater::ObjectDialog:
    file: lib/Slic3r/GUI/Plater/ObjectDialog.pm
    version: 0
  Slic3r::GUI::Plater::ObjectDialog::InfoTab:
    file: lib/Slic3r/GUI/Plater/ObjectDialog.pm
    version: 0
  Slic3r::GUI::Plater::ObjectDialog::LayersTab:
    file: lib/Slic3r/GUI/Plater/ObjectDialog.pm
    version: 0
  Slic3r::GUI::Preferences:
    file: lib/Slic3r/GUI/Preferences.pm
    version: 0
  Slic3r::GUI::ProgressStatusBar:
    file: lib/Slic3r/GUI.pm
    version: 0
  Slic3r::GUI::SavePresetWindow:
    file: lib/Slic3r/GUI/Tab.pm
    version: 0
  Slic3r::GUI::SimpleTab:
    file: lib/Slic3r/GUI/SimpleTab.pm
    version: 0
  Slic3r::GUI::SimpleTab::Filament:
    file: lib/Slic3r/GUI/SimpleTab.pm
    version: 0
  Slic3r::GUI::SimpleTab::Print:
    file: lib/Slic3r/GUI/SimpleTab.pm
    version: 0
  Slic3r::GUI::SimpleTab::Printer:
    file: lib/Slic3r/GUI/SimpleTab.pm
    version: 0
  Slic3r::GUI::SkeinPanel:
    file: lib/Slic3r/GUI/SkeinPanel.pm
    version: 0
  Slic3r::GUI::Tab:
    file: lib/Slic3r/GUI/Tab.pm
    version: 0
  Slic3r::GUI::Tab::Filament:
    file: lib/Slic3r/GUI/Tab.pm
    version: 0
  Slic3r::GUI::Tab::Page:
    file: lib/Slic3r/GUI/Tab.pm
    version: 0
  Slic3r::GUI::Tab::Print:
    file: lib/Slic3r/GUI/Tab.pm
    version: 0
  Slic3r::GUI::Tab::Printer:
    file: lib/Slic3r/GUI/Tab.pm
    version: 0
  Slic3r::Geometry:
    file: lib/Slic3r/Geometry.pm
    version: 0
  Slic3r::Geometry::Clipper:
    file: lib/Slic3r/Geometry/Clipper.pm
    version: 0
  Slic3r::Layer:
    file: lib/Slic3r/Layer.pm
    version: 0
  Slic3r::Layer::Region:
    file: lib/Slic3r/Layer/Region.pm
    version: 0
  Slic3r::Line:
    file: lib/Slic3r/Line.pm
    version: 0
  Slic3r::Model:
    file: lib/Slic3r/Model.pm
    version: 0
  Slic3r::Model::Instance:
    file: lib/Slic3r/Model.pm
    version: 0
  Slic3r::Model::Object:
    file: lib/Slic3r/Model.pm
    version: 0
  Slic3r::Model::Region:
    file: lib/Slic3r/Model.pm
    version: 0
  Slic3r::Model::Volume:
    file: lib/Slic3r/Model.pm
    version: 0
  Slic3r::Point:
    file: lib/Slic3r/Point.pm
    version: 0
  Slic3r::Polygon:
    file: lib/Slic3r/Polygon.pm
    version: 0
  Slic3r::Polyline:
    file: lib/Slic3r/Polyline.pm
    version: 0
  Slic3r::Polyline::Collection:
    file: lib/Slic3r/Polyline.pm
    version: 0
  Slic3r::Print:
    file: lib/Slic3r/Print.pm
    version: 0
  Slic3r::Print::Object:
    file: lib/Slic3r/Print/Object.pm
    version: 0
  Slic3r::Print::Region:
    file: lib/Slic3r/Print/Region.pm
    version: 0
  Slic3r::SVG:
    file: lib/Slic3r/SVG.pm
    version: 0
  Slic3r::Surface:
    file: lib/Slic3r/Surface.pm
    version: 0
  Slic3r::Test:
    file: lib/Slic3r/Test.pm
    version: 0
  Slic3r::Test::GCodeReader:
    file: lib/Slic3r/Test.pm
    version: 0
  Slic3r::TriangleMesh:
    file: lib/Slic3r/TriangleMesh.pm
    version: 0
recommends:
  Class::XSAccessor: 0
  Growl::GNTP: 0.15
  Net::DBus: 0
  Wx: 0.9901
  XML::SAX::ExpatXS: 0
requires:
  Boost::Geometry::Utils: 0.06
  Encode::Locale: 0
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 0
  Math::Clipper: 1.17
  Math::ConvexHull::MonotoneChain: 0.01
  Math::Geometry::Voronoi: 1.3
  Math::PlanePath: 53
  Moo: 0.091009
  Scalar::Util: 0
  Time::HiRes: 0
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
